### ISSUE TITLE
Logo

### ISSUE THREAD

**Issue by JonathanRufino** [JonathanRufino/NotifiCar#11]
We need a new and original logo

**Comment by andeladenaro** [comment]
Hi. I'm Andela Denaro, I would like to contribute new logo for NotifiCar. If you like the logo I will provide you the original files. Here's my logo design.
![notificar](https://user-images.githubusercontent.com/35057858/38190231-88c3b5e6-368d-11e8-8792-cab671bba1ed.png)

**Comment by JonathanRufino** [comment]
Hello @andeladenaro

We are very happy with your contribution, and we liked the icon you proposed.

But i will upload some images from the current app's state for you (we will add an english description soon to README), so you can have a better understanding of the application, and maybe inspire you to change something.
Just to mention, our current design is somehow the default, so we can adjust it to suit your logo.
If you want to suggest something foor our design too we will be very thankfull.

<img src="https://user-images.githubusercontent.com/5273493/38207978-eba2e54a-3685-11e8-9873-24dde3eef2e3.png" width="200" /> <img src="https://user-images.githubusercontent.com/5273493/38208478-92fbe7b4-3687-11e8-8eb9-bfd2c47af7c5.png" width="200" /><img src="https://user-images.githubusercontent.com/5273493/38207976-eb5a9628-3685-11e8-8c5e-cf15002defab.png" width="200" />
<img src="https://user-images.githubusercontent.com/5273493/38207975-eb353202-3685-11e8-92d5-fa8b4c53cb9e.png" width="200" /><img src="https://user-images.githubusercontent.com/5273493/38207974-eb126cfe-3685-11e8-8654-8f34fa3b94af.png" width="200" />

**Comment by andeladenaro** [comment]
So what do you need me to do with the logo? Do you want to change or add something to the logo?

**Comment by JonathanRufino** [comment]
I don't want you to change the logo, I just wanted to show you how the app looks, so maybe you could change something if you thought it needed.

Yeah, I thought about changing the color scheme to match the icon.
Can you send me the the logo icon and the hex/rgba colors used

**Comment by andeladenaro** [comment]
yes sure, here you go. https://drive.google.com/open?id=14A9IDwOmlukHalblIojzEsvY8YhpWNbc
Let me know if you need another file size.

**Comment by andeladenaro** [comment]
Can you tell me main feature of NotifiCar? So I can help you with the UI/UX too.

**Comment by JonathanRufino** [comment]
We have added a description to README.md

https://github.com/JonathanRufino/NotifiCar/blob/ios_push_notification/README.md#description

But, in other words, let's assume you have a car.
After parking it, maybe you forget to turn off the lights, or close a window for example, and leave.
Perhaps someone can see it, but will not be able to find you to tell. Instead, that person can register it 
to the app and you will be warned by a push notification.

**Comment by JonathanRufino** [comment]
Can you provide the Icon > icons_full-colour in 1024x1024 size?

**Comment by andeladenaro** [comment]
Sure, I've uploaded to the [drive](https://drive.google.com/open?id=14A9IDwOmlukHalblIojzEsvY8YhpWNbc).

**Comment by JonathanRufino** [comment]
@andeladenaro can i have your name? I will add to CONTRIBUTORS.md

**Comment by andeladenaro** [comment]
Andela Denaro is okay. Thank you.

**Comment by andeladenaro** [comment]
Hi Jonathan.
Can you show me where I can find the License? I just want to make sure I contribute to the open source project.
